# Generated by Django 5.2 on 2025-05-10 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(blank=True, max_length=100)),
                ('facebook_link', models.URLField(blank=True)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('vjudge_username', models.CharField(blank=True, max_length=100)),
                ('codeforces_username', models.CharField(blank=True, max_length=100)),
                ('total_unique_solves', models.PositiveIntegerField(default=0)),
                ('codeforces_max_rating', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
