# Generated by Django 5.2 on 2025-04-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('editorial_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('code_link', models.URLField(blank=True, null=True)),
                ('timer', models.IntegerField(default=0)),
                ('ac_rate', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('starred', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
