# Generated by Django 5.2 on 2025-04-27 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0002_problem_delete_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
