# Generated by Django 5.2 on 2025-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0003_problem_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], default='not_started', max_length=20),
        ),
    ]
