# Generated by Django 5.2 on 2025-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0004_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
