# Generated by Django 5.2 on 2025-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0005_problem_external_url_problem_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
