# Generated by Django 5.2 on 2025-05-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0006_alter_problem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code_link',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
