# Generated by Django 5.2 on 2025-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0007_alter_problem_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code_link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
