# Generated by Django 5.2 on 2025-05-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0008_alter_problem_code_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='code_link',
            new_name='code',
        ),
    ]
