# Generated by Django 5.2 on 2025-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0009_rename_code_link_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
