# Generated by Django 5.2 on 2025-05-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0011_problemstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatus',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list_problem_statuses', to='problem_list.problem'),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list_problem_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
