# Generated by Django 5.2 on 2025-05-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], default='not_started', max_length=20)),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
    ]
