# Generated by Django 5.2 on 2025-05-10 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('problem_list', '0010_alter_problem_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], default='not_started', max_length=20)),
                ('timer', models.IntegerField(default=0)),
                ('bookmarked', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_list.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.DeleteModel(
            name='ProblemStatusSummary',
        ),
    ]
