# Generated by Django 5.2 on 2025-05-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_problemstatus_delete_problemstatussummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemstatus',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='problemstatus',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='problemstatus',
            name='timer',
        ),
    ]
