# Generated by Django 5.2 on 2025-05-10 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_problemstatus_unique_together_and_more'),
        ('problem_list', '0011_problemstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatus',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_problem_statuses', to='problem_list.problem'),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_problem_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='problemstatus',
            unique_together={('user', 'problem')},
        ),
    ]
